// Run against a disposable CASEHUB_STORE=memory server, never production data.
// PLAYWRIGHT_MODULE may point to an existing Playwright installation.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict');
(async()=>{
  const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
  try {
    const page=await browser.newPage();
    const errors=[];
    page.on('pageerror',e=>errors.push(e.stack||e.message));
    await page.goto(process.env.CASEHUB_TEST_URL||'http://127.0.0.1:18081');
    await page.locator('#revision').filter({hasText:'主线 r'}).waitFor();
    await page.locator('#collapse').click();
    assert.equal(await page.locator('#empty-expand').isVisible(),true);
    assert.ok((await page.locator('#content').boundingBox()).width>1000);
    await page.locator('#empty-expand').click();
    assert.equal(await page.locator('#sidebar').isVisible(),true);
    await page.locator('.folder-row').first().click();
    const folderHTML=await page.locator('#detail').innerHTML();
    await page.locator('#collapse').click();
    assert.equal(await page.locator('#detail').innerHTML(),folderHTML);
    assert.ok((await page.locator('#content').boundingBox()).width>1000);
    await page.locator('#expand').click();
    assert.equal(await page.locator('.tree-row').filter({hasText:'◇'}).count(),0);
    await page.locator('#create-version').click();
    await page.locator('[name="Name"]').fill(`UI 验证 ${Date.now()}`);
    await page.locator('#modal-form button[type="submit"]').click();
    await page.locator('#modal').waitFor({state:'hidden'});
    const branch=page.locator('.version').last();
    await branch.locator('.case-row').first().click();
    assert.equal(await branch.locator('.case-check').count(),2);
    const caseHTML=await page.locator('#detail').innerHTML();
    const splitter=await page.locator('#resize-left').boundingBox();
    await page.mouse.move(splitter.x+2,splitter.y+100);
    await page.mouse.down();await page.mouse.move(20,splitter.y+100);await page.mouse.up();
    assert.equal(await page.locator('#detail').innerHTML(),caseHTML);
    assert.ok((await page.locator('#content').boundingBox()).width>1000);
    await page.locator('#expand').click();
    await page.evaluate(()=>openSearch(focus.versionID));
    await page.locator('#run-search').click();
    await page.locator('#collapse').click();
    assert.equal(await page.locator('#detail').innerHTML(),caseHTML);
    const searchBox=await page.locator('#search-panel').boundingBox(),contentBox=await page.locator('#content').boundingBox();
    assert.ok(contentBox.x>=searchBox.x+searchBox.width);
    await page.locator('#close-search').click();
    assert.ok((await page.locator('#content').boundingBox()).width>1000);
    await page.locator('#expand').click();
    await page.locator('#edit-case').click();
    await page.locator('[name="Title"]').fill('历史快照验证 <安全文本>');
    await page.locator('#modal-form button[type="submit"]').click();
    await page.locator('#modal').waitFor({state:'hidden'});
    await page.locator('.history-row').first().click();
    await page.locator('.history-snapshot').waitFor();
    assert.match(await page.locator('.history-snapshot').innerText(),/历史快照验证 <安全文本>/);
    assert.match(await page.locator('.changed').first().innerText(),/正确账号密码登录/);
    await page.reload();
    await page.locator('.history-snapshot').waitFor();
    await page.getByRole('link',{name:'← 返回用例详情'}).click();
    await page.locator('#open-record').click();
    await page.locator('.toastui-editor-ww-container [contenteditable="true"]').fill('富文本记录');
    const note='## 执行环境\n\n**加粗结果**\n\n- 检查登录\n\n[链接](https://example.com)';
    await page.evaluate(note=>recordEditor.setMarkdown(note),note);
    await page.getByText('Markdown',{exact:true}).click();
    assert.equal(await page.evaluate(()=>recordEditor.isMarkdownMode()),true);
    await page.getByText('所见即所得',{exact:true}).click();
    await page.locator('#save-draft').click();
    await page.locator('.record').filter({hasText:'草稿'}).waitFor();
    assert.equal(await page.locator('.record[open]').count(),0);
    await page.locator('.record summary').first().click();
    assert.equal(await page.locator('.record-note strong').first().innerText(),'加粗结果');
    await page.locator('#theme').click();
    assert.match(await page.evaluate(()=>recordEditor.getMarkdown()),/加粗结果/);
    await page.locator('#record-form button[type="submit"]').click();
    await page.locator('.record').filter({hasText:'已提交'}).waitFor();
    assert.equal(await page.locator('.record [contenteditable="true"]').count(),0);
    const state=await page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
    const submitted=state.records.find(r=>r.Submitted);
    assert.equal(submitted.Result,'passed');
    assert.match(submitted.Note,/\*\*加粗结果\*\*/);
    assert.equal(await page.evaluate(()=>recordEditor.getMarkdown()),'');
    for(let i=0;i<3;i++){
      await page.evaluate(i=>recordEditor.setMarkdown(`较新记录 ${i}`),i);
      await page.locator('#save-draft').click();
      await page.waitForFunction(()=>!document.querySelector('#save-draft').disabled);
    }
    assert.equal(await page.locator('.record').count(),3);
    assert.match(await page.locator('.record summary').first().innerText(),/较新记录 2/);
    await page.evaluate(()=>recordEditor.setMarkdown('未保存内容'));
    await page.locator('#toggle-record-history').click();
    assert.equal(await page.locator('.record').count(),5);
    await page.locator('.record summary').last().click();
    assert.equal(await page.locator('.record').last().locator('strong').innerText(),'加粗结果');
    await page.locator('#toggle-record-history').click();
    assert.equal(await page.locator('.record').count(),3);
    assert.equal(await page.evaluate(()=>recordEditor.getMarkdown()),'未保存内容');
    await page.locator('#drawer-close').click();
    await page.locator('#open-record').click();
    assert.equal(await page.evaluate(()=>recordEditor.getMarkdown()),'');
    await page.locator('#drawer-close').click();
    await page.getByRole('link',{name:'API 文档'}).click();
    await page.getByRole('heading',{name:'后端 API',exact:true}).waitFor();
    assert.equal(await page.locator('details').count(),10);
    assert.equal(await page.locator('html').getAttribute('class'),'dark');
    const nav=page.getByRole('navigation',{name:'API 文档导航'});
    assert.equal(await nav.locator('a').count(),13);
    const navBox=await nav.boundingBox(),docsBox=await page.locator('.api-docs').boundingBox();
    assert.ok(navBox.x+navBox.width<=docsBox.x);
    await nav.getByRole('link',{name:'提交测试记录'}).click();
    await page.waitForFunction(()=>document.querySelector('#submitRecord').open);
    assert.equal(await nav.locator('[aria-current]').getAttribute('href'),'#submitRecord');
    await page.reload();
    await page.waitForFunction(()=>document.querySelector('#submitRecord').open);
    await page.locator('#submitRecord summary').click();
    await nav.getByRole('link',{name:'提交测试记录'}).click();
    await page.waitForFunction(()=>document.querySelector('#submitRecord').open);
    assert.match(await page.locator('#submitRecord pre').innerText(),/"Note"/);
    assert.deepEqual(errors,[]);
    console.log('PASS: case icons, history navigation/reload, rich text, Markdown persistence, immutable records, discard, theme, API docs');
  } finally {await browser.close()}
})().catch(e=>{console.error(e);process.exit(1)});
